const services = [
    { id: 1, name: "Telegram", icon: "fab fa-telegram", users: "700M", country: "Офшор", risk: "Высокий", category: "мессенджер" },
    { id: 2, name: "YouTube", icon: "fab fa-youtube", users: "2.5B", country: "USA", risk: "Средний", category: "видео" },
    { id: 3, name: "TikTok", icon: "fab fa-tiktok", users: "1.5B", country: "Китай", risk: "Высокий", category: "соцсеть" },
    { id: 4, name: "WhatsApp", icon: "fab fa-whatsapp", users: "2B", country: "USA", risk: "Низкий", category: "мессенджер" },
    { id: 5, name: "Instagram", icon: "fab fa-instagram", users: "1.2B", country: "USA", risk: "Средний", category: "соцсеть" },
    { id: 6, name: "Twitter", icon: "fab fa-twitter", users: "450M", country: "USA", risk: "Высокий", category: "соцсеть" },
    { id: 7, name: "Discord", icon: "fab fa-discord", users: "150M", country: "USA", risk: "Средний", category: "мессенджер" },
    { id: 8, name: "Steam", icon: "fab fa-steam", users: "132M", country: "USA", risk: "Высокий", category: "игры" },
    { id: 9, name: "Roblox", icon: "fas fa-gamepad", users: "202M", country: "USA", risk: "Высокий", category: "игры" },
    { id: 10, name: "Minecraft", icon: "fas fa-cube", users: "141M", country: "Швеция", risk: "Средний", category: "игры" },
    { id: 11, name: "Fortnite", icon: "fas fa-bullseye", users: "350M", country: "USA", risk: "Высокий", category: "игры" },
    { id: 12, name: "Valorant", icon: "fas fa-crosshairs", users: "20M", country: "USA", risk: "Высокий", category: "игры" },
    { id: 13, name: "CS:GO", icon: "fas fa-gun", users: "35M", country: "USA", risk: "Средний", category: "игры" },
    { id: 14, name: "Dota 2", icon: "fas fa-sword", users: "11M", country: "USA", risk: "Средний", category: "игры" },
    { id: 15, name: "League of Legends", icon: "fas fa-fist-raised", users: "150M", country: "USA", risk: "Высокий", category: "игры" },
    { id: 16, name: "Epic Games", icon: "fas fa-ghost", users: "230M", country: "USA", risk: "Средний", category: "игры" },
    { id: 17, name: "Battle.net", icon: "fas fa-crosshairs", users: "90M", country: "USA", risk: "Средний", category: "игры" },
    { id: 18, name: "Origin", icon: "fas fa-dice", users: "50M", country: "USA", risk: "Низкий", category: "игры" },
    { id: 19, name: "Xbox Live", icon: "fab fa-xbox", users: "100M", country: "USA", risk: "Низкий", category: "игры" },
    { id: 20, name: "PlayStation", icon: "fab fa-playstation", users: "112M", country: "Япония", risk: "Низкий", category: "игры" },
    { id: 21, name: "Nintendo", icon: "fas fa-gamepad", users: "125M", country: "Япония", risk: "Низкий", category: "игры" },
    { id: 22, name: "Ubisoft", icon: "fas fa-umbrella", users: "45M", country: "Франция", risk: "Низкий", category: "игры" },
    { id: 23, name: "EA Sports", icon: "fas fa-futbol", users: "65M", country: "USA", risk: "Низкий", category: "игры" },
    { id: 24, name: "Rockstar Games", icon: "fas fa-star", users: "85M", country: "USA", risk: "Высокий", category: "игры" },
    { id: 25, name: "Zoom", icon: "fas fa-video", users: "300M", country: "USA", risk: "Средний", category: "коммуникация" },
    { id: 26, name: "Skype", icon: "fab fa-skype", users: "100M", country: "USA", risk: "Низкий", category: "коммуникация" },
    { id: 27, name: "Microsoft Teams", icon: "fas fa-users", users: "270M", country: "USA", risk: "Низкий", category: "коммуникация" },
    { id: 28, name: "Slack", icon: "fab fa-slack", users: "20M", country: "USA", risk: "Низкий", category: "коммуникация" },
    { id: 29, name: "Google Meet", icon: "fab fa-google", users: "100M", country: "USA", risk: "Низкий", category: "коммуникация" },
    { id: 30, name: "Viber", icon: "fas fa-phone-alt", users: "260M", country: "Япония", risk: "Низкий", category: "мессенджер" },
    { id: 31, name: "WeChat", icon: "fab fa-weixin", users: "1.3B", country: "Китай", risk: "Высокий", category: "мессенджер" },
    { id: 32, name: "LINE", icon: "fas fa-comment", users: "84M", country: "Япония", risk: "Средний", category: "мессенджер" },
    { id: 33, name: "Signal", icon: "fas fa-lock", users: "40M", country: "USA", risk: "Высокий", category: "мессенджер" },
    { id: 34, name: "Facebook", icon: "fab fa-facebook", users: "2.9B", country: "USA", risk: "Высокий", category: "соцсеть" },
    { id: 35, name: "Snapchat", icon: "fab fa-snapchat", users: "375M", country: "USA", risk: "Высокий", category: "соцсеть" },
    { id: 36, name: "Reddit", icon: "fab fa-reddit", users: "430M", country: "USA", risk: "Высокий", category: "соцсеть" },
    { id: 37, name: "LinkedIn", icon: "fab fa-linkedin", users: "900M", country: "USA", risk: "Средний", category: "соцсеть" },
    { id: 38, name: "Pinterest", icon: "fab fa-pinterest", users: "445M", country: "USA", risk: "Низкий", category: "соцсеть" },
    { id: 39, name: "Tumblr", icon: "fab fa-tumblr", users: "135M", country: "USA", risk: "Высокий", category: "соцсеть" },
    { id: 40, name: "Twitch", icon: "fab fa-twitch", users: "140M", country: "USA", risk: "Высокий", category: "стриминг" },
    { id: 41, name: "YouTube Music", icon: "fab fa-youtube", users: "50M", country: "USA", risk: "Низкий", category: "музыка" },
    { id: 42, name: "Spotify", icon: "fab fa-spotify", users: "180M", country: "Швеция", risk: "Низкий", category: "музыка" },
    { id: 43, name: "Apple Music", icon: "fab fa-apple", users: "88M", country: "USA", risk: "Низкий", category: "музыка" },
    { id: 44, name: "SoundCloud", icon: "fab fa-soundcloud", users: "76M", country: "Германия", risk: "Средний", category: "музыка" },
    { id: 45, name: "Deezer", icon: "fas fa-music", users: "14M", country: "Франция", risk: "Низкий", category: "музыка" },
    { id: 46, name: "Netflix", icon: "fas fa-film", users: "230M", country: "USA", risk: "Средний", category: "видео" },
    { id: 47, name: "Amazon Prime", icon: "fab fa-amazon", users: "200M", country: "USA", risk: "Низкий", category: "видео" },
    { id: 48, name: "Disney+", icon: "fas fa-film", users: "150M", country: "USA", risk: "Низкий", category: "видео" },
    { id: 49, name: "HBO Max", icon: "fas fa-tv", users: "76M", country: "USA", risk: "Средний", category: "видео" },
    { id: 50, name: "Hulu", icon: "fas fa-video", users: "45M", country: "USA", risk: "Низкий", category: "видео" },
    { id: 51, name: "Google Drive", icon: "fab fa-google-drive", users: "1B", country: "USA", risk: "Средний", category: "облако" },
    { id: 52, name: "Dropbox", icon: "fab fa-dropbox", users: "700M", country: "USA", risk: "Низкий", category: "облако" },
    { id: 53, name: "OneDrive", icon: "fas fa-cloud", users: "250M", country: "USA", risk: "Низкий", category: "облако" },
    { id: 54, name: "iCloud", icon: "fab fa-apple", users: "850M", country: "USA", risk: "Низкий", category: "облако" },
    { id: 55, name: "Mega", icon: "fas fa-cloud-upload-alt", users: "250M", country: "Новая Зеландия", risk: "Высокий", category: "облако" },
    { id: 56, name: "GitHub", icon: "fab fa-github", users: "100M", country: "USA", risk: "Высокий", category: "разработка" },
    { id: 57, name: "GitLab", icon: "fab fa-gitlab", users: "30M", country: "USA", risk: "Высокий", category: "разработка" },
    { id: 58, name: "Bitbucket", icon: "fab fa-bitbucket", users: "10M", country: "Австралия", risk: "Средний", category: "разработка" },
    { id: 59, name: "Stack Overflow", icon: "fab fa-stack-overflow", users: "100M", country: "USA", risk: "Низкий", category: "разработка" },
    { id: 60, name: "Docker", icon: "fab fa-docker", users: "13M", country: "USA", risk: "Средний", category: "разработка" },
    { id: 61, name: "PayPal", icon: "fab fa-paypal", users: "430M", country: "USA", risk: "Средний", category: "финансы" },
    { id: 62, name: "Stripe", icon: "fab fa-stripe", users: "3M", country: "USA", risk: "Низкий", category: "финансы" },
    { id: 63, name: "Wise", icon: "fas fa-money-bill-wave", users: "16M", country: "UK", risk: "Низкий", category: "финансы" },
    { id: 64, name: "Revolut", icon: "fas fa-credit-card", users: "25M", country: "UK", risk: "Высокий", category: "финансы" },
    { id: 65, name: "AliExpress", icon: "fas fa-shopping-cart", users: "150M", country: "Китай", risk: "Средний", category: "шопинг" },
    { id: 66, name: "Amazon", icon: "fab fa-amazon", users: "300M", country: "USA", risk: "Низкий", category: "шопинг" },
    { id: 67, name: "eBay", icon: "fab fa-ebay", users: "185M", country: "USA", risk: "Низкий", category: "шопинг" },
    { id: 68, name: "Wildberries", icon: "fas fa-shopping-bag", users: "40M", country: "РФ", risk: "Низкий", category: "шопинг" },
    { id: 69, name: "Ozon", icon: "fas fa-box", users: "25M", country: "РФ", risk: "Низкий", category: "шопинг" },
    { id: 70, name: "Avito", icon: "fas fa-tag", users: "35M", country: "РФ", risk: "Средний", category: "шопинг" },
    { id: 71, name: "VKontakte", icon: "fab fa-vk", users: "97M", country: "РФ", risk: "Средний", category: "соцсеть" },
    { id: 72, name: "Одноклассники", icon: "fas fa-users", users: "71M", country: "РФ", risk: "Низкий", category: "соцсеть" },
    { id: 73, name: "Яндекс", icon: "fas fa-search", users: "60M", country: "РФ", risk: "Низкий", category: "поиск" },
    { id: 74, name: "Google", icon: "fab fa-google", users: "4B", country: "USA", risk: "Высокий", category: "поиск" },
    { id: 75, name: "Bing", icon: "fab fa-microsoft", users: "1B", country: "USA", risk: "Низкий", category: "поиск" },
    { id: 76, name: "DuckDuckGo", icon: "fas fa-search", users: "100M", country: "USA", risk: "Высокий", category: "поиск" },
    { id: 77, name: "Wikipedia", icon: "fab fa-wikipedia-w", users: "1.7B", country: "USA", risk: "Средний", category: "знания" },
    { id: 78, name: "Quora", icon: "fab fa-quora", users: "300M", country: "USA", risk: "Средний", category: "знания" },
    { id: 79, name: "Medium", icon: "fab fa-medium", users: "60M", country: "USA", risk: "Высокий", category: "блоги" },
    { id: 80, name: "WordPress", icon: "fab fa-wordpress", users: "60M", country: "USA", risk: "Средний", category: "блоги" },
    { id: 81, name: "Tinder", icon: "fas fa-heart", users: "75M", country: "USA", risk: "Высокий", category: "знакомства" },
    { id: 82, name: "Bumble", icon: "fas fa-heart", users: "50M", country: "USA", risk: "Средний", category: "знакомства" },
    { id: 83, name: "Grindr", icon: "fas fa-user-friends", users: "13M", country: "USA", risk: "Высокий", category: "знакомства" },
    { id: 84, name: "OnlyFans", icon: "fas fa-star", users: "2M", country: "UK", risk: "Высокий", category: "стриминг" },
    { id: 85, name: "Patreon", icon: "fab fa-patreon", users: "8M", country: "USA", risk: "Средний", category: "стриминг" },
    { id: 86, name: "Clubhouse", icon: "fas fa-broadcast-tower", users: "10M", country: "USA", risk: "Высокий", category: "аудио" },
    { id: 87, name: "9GAG", icon: "fas fa-laugh", users: "150M", country: "Гонконг", risk: "Средний", category: "развлечения" },
    { id: 88, name: "Imgur", icon: "fas fa-image", users: "250M", country: "USA", risk: "Средний", category: "развлечения" },
    { id: 89, name: "GIPHY", icon: "fas fa-film", users: "300M", country: "USA", risk: "Низкий", category: "развлечения" },
    { id: 90, name: "Shazam", icon: "fas fa-music", users: "200M", country: "USA", risk: "Низкий", category: "музыка" },
    { id: 91, name: "Strava", icon: "fas fa-running", users: "100M", country: "USA", risk: "Низкий", category: "спорт" },
    { id: 92, name: "MyFitnessPal", icon: "fas fa-apple-alt", users: "200M", country: "USA", risk: "Низкий", category: "здоровье" },
    { id: 93, name: "Headspace", icon: "fas fa-brain", users: "70M", country: "USA", risk: "Низкий", category: "здоровье" },
    { id: 94, name: "Calm", icon: "fas fa-spa", users: "100M", country: "USA", risk: "Низкий", category: "здоровье" },
    { id: 95, name: "Duolingo", icon: "fas fa-language", users: "74M", country: "USA", risk: "Низкий", category: "образование" },
    { id: 96, name: "Coursera", icon: "fas fa-graduation-cap", users: "92M", country: "USA", risk: "Низкий", category: "образование" },
    { id: 97, name: "Udemy", icon: "fas fa-book", users: "59M", country: "USA", risk: "Низкий", category: "образование" },
    { id: 98, name: "Khan Academy", icon: "fas fa-chalkboard-teacher", users: "120M", country: "USA", risk: "Низкий", category: "образование" },
    { id: 99, name: "Booking.com", icon: "fas fa-hotel", users: "100M", country: "Нидерланды", risk: "Низкий", category: "путешествия" },
    { id: 100, name: "Airbnb", icon: "fas fa-home", users: "150M", country: "USA", risk: "Средний", category: "путешествия" }
];

let availableServices = [...services];
let blockedServices = [];
let currentService = null;
let isSpinning = false;